In [2]:
import pandas as pd
df=pd.read_json(r"C:\Users\annad\Documents\AI-Powered Code Generator\MLcode_Dataset.jsonl")

In [3]:
df.head()

,natural_language,code
0,Generate Python code to implement Linear Regre...,from sklearn.linear_model import LinearRegress...
1,Create a program for Logistic Regression with ...,from sklearn.linear_model import LogisticRegre...
2,Write code to implement Decision Tree Classifi...,from sklearn.tree import DecisionTreeClassifie...
3,Produce Python program to perform Support Vect...,from sklearn.svm import SVC\nfrom sklearn.data...
4,Build code for K-Nearest Neighbors classifier ...,from sklearn.neighbors import KNeighborsClassi...


In [6]:
df.to_csv(r"C:\Users\annad\Documents\AI-Powered Code Generator\code.csv")

In [ ]:
from transformers import T5tokenizor
from transformers import Autotokinizer

In [14]:
df["code"].iloc[1:8]

1    from sklearn.linear_model import LogisticRegre...
2    from sklearn.tree import DecisionTreeClassifie...
3    from sklearn.svm import SVC\nfrom sklearn.data...
4    from sklearn.neighbors import KNeighborsClassi...
5    from sklearn.ensemble import RandomForestClass...
6    from sklearn.ensemble import GradientBoostingC...
7    from sklearn.ensemble import AdaBoostClassifie...
Name: code, dtype: object

In [16]:
df["pre1"]=[i.lower().strip() for i in df["natural_language"]]

In [17]:
df["pre1"]

0     generate python code to implement linear regre...
1     create a program for logistic regression with ...
2     write code to implement decision tree classifi...
3     produce python program to perform support vect...
4     build code for k-nearest neighbors classifier ...
                            ...                        
69    create python program to implement adaboost cl...
70    generate code to implement polynomial feature ...
71    write python program to apply baggingclassifie...
72    create python code to train a neural network u...
73    generate python code to perform text preproces...
Name: pre1, Length: 74, dtype: object

In [ ]:
input=[i.lower().strip() for i in df["natural_language"]]
output=[j.lower().strip() for j in df["code"]]

In [21]:
input

['generate python code to implement linear regression and test it on a sample dataset',
 'create a program for logistic regression with sample data and print accuracy',
 'write code to implement decision tree classifier and evaluate with sample data',
 'produce python program to perform support vector machine classification',
 'build code for k-nearest neighbors classifier with sample data',
 'create program to implement random forest classifier on sample data',
 'write code for gradient boosting classifier with verification on sample data',
 'implement adaboost classifier with sample data and output accuracy',
 'create python code to perform naive bayes classification on sample dataset',
 'produce code for linear discriminant analysis with verification data',
 'write program to implement quadratic discriminant analysis with sample data',
 'build python program for perceptron classifier with test data',
 'create program for stochastic gradient descent classifier with sample dataset',
 

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [24]:
vect_in=CountVectorizer()
vect_out=CountVectorizer()
X=vect_in.fit_transform(input).toarray()
Y=vect_out.fit_transform(output).toarray()

In [25]:
X.shape

(74, 181)

In [26]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [28]:
def predict(inp):
    x_vec = vect_in.transform([inp]).toarray()
    y_pred=model.predict(x_vec)
    idx=np.argmax(np.dot(vect_out.transform(output).toarray(),y_pred.T))
    return output[idx]

In [34]:
print(predict("generate code for dimensolity reduction"))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import logisticregression
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# load data
data = load_iris()
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, random_state=42)

# train model
model = logisticregression(max_iter=1000)
model.fit(x_train, y_train)

# predict
y_pred = model.predict(x_test)

# compute confusion matrix
cm = confusion_matrix(y_test, y_pred)

# plot
sns.heatmap(cm, annot=true, fmt='d')
plt.title('confusion matrix')
plt.xlabel('predicted')
plt.ylabel('actual')
plt.show()


In [36]:
from sklearn.preprocessing import LabelEncoder 
label_encoder = LabelEncoder()
y=label_encoder.fit_transform(output)
print(y)

[43 46 65 64 57 38 32 26 56 24 25 49 51 48 60 28 30 34 23 53 22  3  1  2
 55 35 62 44 50 42 41 40 52 58 31 27 29 33 36 63 45 37 47 11 14 21 12 59
 18 17 71 61 70 72 68 39 66 13 54 20  8  0  6 16 10 19 15 67  9  5  4  7
 73 69]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(input).toarray()

In [39]:
print(x)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.41863399 0.         0.         ... 0.         0.19073771 0.        ]
 [0.         0.         0.         ... 0.         0.19512978 0.24255439]
 ...
 [0.         0.         0.         ... 0.         0.         0.23150904]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.13522585 0.        ]]


In [41]:
from tensorflow.keras.models import Sequential

c:\Users\annad\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.30.2 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\annad\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.30.2 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\annad\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.30.2 at tensorflow/core/framewo

In [42]:
from tensorflow.keras.layers import Dense

In [53]:
model = Sequential([Dense(64,activation='relu',input_shape=(x.shape[1],)),Dense(32,activation='relu'),Dense(len(set(y)),activation='softmax')])

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(X,y,epochs=50,verbose=0)

c:\Users\annad\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [51]:
def pred(user_inp):
    x_vect=vectorizer.transform([user_inp]).toarray()
    pred=model.predict(x_vect)
    code_idx=np.argmax(pred)
    return label_encoder.inverse_transform([code_idx])[0]



In [54]:
print(pred("generate code for k-means clustering"))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
from sklearn.cluster import kmeans
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

# generate sample data
x, y = make_blobs(n_samples=300, centers=4, random_state=42)

# initialize and fit kmeans
kmeans = kmeans(n_clusters=4, random_state=42)
kmeans.fit(x)

# plot the clustering result
plt.scatter(x[:, 0], x[:, 1], c=kmeans.labels_)
plt.title('k-means clustering')
plt.show()


In [48]:
df.head(10)

,natural_language,code,pre1
0,Generate Python code to implement Linear Regre...,from sklearn.linear_model import LinearRegress...,generate python code to implement linear regre...
1,Create a program for Logistic Regression with ...,from sklearn.linear_model import LogisticRegre...,create a program for logistic regression with ...
2,Write code to implement Decision Tree Classifi...,from sklearn.tree import DecisionTreeClassifie...,write code to implement decision tree classifi...
3,Produce Python program to perform Support Vect...,from sklearn.svm import SVC\nfrom sklearn.data...,produce python program to perform support vect...
4,Build code for K-Nearest Neighbors classifier ...,from sklearn.neighbors import KNeighborsClassi...,build code for k-nearest neighbors classifier ...
5,Create program to implement Random Forest Clas...,from sklearn.ensemble import RandomForestClass...,create program to implement random forest clas...
6,Write code for Gradient Boosting Classifier wi...,from sklearn.ensemble import GradientBoostingC...,write code for gradient boosting classifier wi...
7,Implement AdaBoost Classifier with sample data...,from sklearn.ensemble import AdaBoostClassifie...,implement adaboost classifier with sample data...
8,Create Python code to perform Naive Bayes clas...,from sklearn.naive_bayes import GaussianNB\nfr...,create python code to perform naive bayes clas...
9,Produce code for Linear Discriminant Analysis ...,from sklearn.discriminant_analysis import Line...,produce code for linear discriminant analysis ...


In [55]:
print(pred("generate code for principal component analysis (pca) in python"))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
from sklearn.decomposition import pca
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

# load iris dataset
data = load_iris()
x = data.data

# initialize and fit pca
pca = pca(n_components=2)
x_pca = pca.fit_transform(x)

# plot the pca result
plt.scatter(x_pca[:, 0], x_pca[:, 1], c=data.target)
plt.xlabel('pc1')
plt.ylabel('pc2')
plt.title('pca on iris dataset')
plt.show()
